"""

This script:
1. Reads chart_data.json (generated by data_preparation.py)
2. Reads dashboard_template.html (the Jinja2 HTML template)
3. Injects chart JSON + KPI values + district stats into the template
4. Bundles Plotly.js inline (no internet required)
5. Saves the final dashboard.html ready to open in browser

Usage:
    Step 1: python data_preparation.py
    Step 2: python generate_dashboard.py
    Step 3: Open dashboard.html in browser
"""

import json
import os
from jinja2 import Template

# ── STEP 1: Load chart data ────────────────────────────────────────────
print("Loading chart data...")
with open("chart_data.json", "r") as f:
    data = json.load(f)

charts_raw  = data["charts"]
kpis        = data["kpis"]
dist_stats  = data.get("dist_stats", {})

# Support fig1–fig8
charts = {}
for i in range(1, 13):
    key = f"fig{i}"
    charts[key] = charts_raw.get(key, "")

print(f"  KPIs loaded:   {list(kpis.keys())}")
print(f"  Charts loaded: {[k for k,v in charts.items() if v]}")
print(f"  Dist stats:    {list(dist_stats.keys())}")

# ── STEP 2: Load Plotly.js ─────────────────────────────────────────────
print("\nLoading Plotly.js bundle...")
try:
    import plotly
    plotly_js_path = os.path.join(
        os.path.dirname(plotly.__file__), "package_data", "plotly.min.js"
    )
    with open(plotly_js_path, "r") as f:
        plotly_js = f.read()
    print(f"  Plotly.js loaded ({len(plotly_js)/1024/1024:.1f} MB)")
except Exception as e:
    print(f"  ERROR loading Plotly.js: {e}")
    exit(1)

# ── STEP 3: Load template ─────────────────────────────────────────────
print("\nLoading HTML template...")
with open("dashboard_template.html", "r") as f:
    template_source = f.read()

# ── STEP 4: Jinja2 render for KPIs + dist_stats ───────────────────────
print("Rendering Jinja2 template...")
html = Template(template_source).render(
    kpis=kpis,
    dist_stats=dist_stats
)

# ── STEP 5: String-replace chart JSON + Plotly JS ────────────────────
# (avoids Jinja2 escaping issues with large JSON blobs)
print("Injecting chart data...")

for i in range(1, 13):
    placeholder = f"%%CHART_FIG{i}%%"
    html = html.replace(placeholder, charts[f"fig{i}"])

html = html.replace("%%DIST_STATS%%", json.dumps(dist_stats))
html = html.replace("%%PLOTLY_JS%%",  plotly_js)

# ── STEP 6: Save ──────────────────────────────────────────────────────
output_path = "dashboard.html"
with open(output_path, "w", encoding="utf-8") as f:
    f.write(html)

size_mb = os.path.getsize(output_path) / 1024 / 1024
print(f"\n✅ Dashboard saved: {output_path} ({size_mb:.1f} MB)")
print("   Open dashboard.html in your browser to view it.")
